-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 18:56:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`CLIENTE` (
  `CPF` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `DATANASC` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`CONTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`CONTA` (
  `AGENCIA` INT NOT NULL,
  `CONTACORRENTE` VARCHAR(45) NOT NULL,
  `SALDO` DOUBLE NOT NULL,
  `CLIENTE_CPF` INT NOT NULL,
  INDEX `fk_CONTA_CLIENTE_idx` (`CLIENTE_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_CONTA_CLIENTE`
    FOREIGN KEY (`CLIENTE_CPF`)
    REFERENCES `banco`.`CLIENTE` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
